* TODO Template for assets like the Tcl Tk initialisation source file and whatnot.

From <ircs://irc.libera.chat/guile>:

#+begin_quote
2024-06-16T23:33:11+0000 < cow_2001> i have a piece of Tcl code lying about in pstk.scm as a string and i want to take it out and put it in a dedicated Tcl file.  how do i find the location of this kind of non-scm file assets within to my package, then?
[…]
2024-06-16T23:43:14+0000 < flatwhatson> cow_2001: you could hunt for things at runtime along %load-path and friends, or use the traditional approach of determining the path at configure time and embedding it into your package
2024-06-16T23:45:41+0000 < flatwhatson> ie. using a config.scm.in template with a @PATH_TO_MY_THING@, eg. https://git.dthompson.us/chickadee/tree/chickadee/config.scm.in
2024-06-16T23:45:55+0000 < cow_2001> oh boy.  autotools template!
2024-06-16T23:46:08+0000 < cow_2001> that'll be a new one for me
2024-06-16T23:48:14+0000 < cow_2001> flatwhatson: thank you!
#+end_quote

* TODO Modernisation of Tk?

- Some ideas?  (I haven't read yet.  Don't even know if it's something we should or shouldn't do.):
  https://medium.com/@roy-chng/make-python-tkinter-applications-look-modern-eb9d25a8e7bb

* TODO Reading resources:

https://www.tcl.tk/doc/
https://www.peter-herth.de/ltk/ltkdoc/
https://tkdocs.com/tutorial/intro.html
